# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/JSON-JOM-Plugins-YAML/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61" ;
	:requires "JSON 2.00", "JSON::JOM 0.500", "JSON::JOM::Plugins::Dumper",
		"Object::AUTHORITY", "YAML::Any" .

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/JSON/JOM/Plugins/YAML.pm" .

